config/routes.rb
Factory::Application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :front
  resources :tags
  resources :authors

  root 'front#index'

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    article_params = params.require(:article).permit(:title, :body, :tag_list, :image)
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article '#{@article.title}' Deleted!"
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    article_params = params.require(:article).permit(:title, :body, :tag_list, :image)
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"
    redirect_to article_path(@article)
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:email, :username, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  comment_params = params.require(:comment).permit(:author_name, :body)
  @comment = Comment.new(comment_params)
  @comment.article_id = params[:article_id]

  @comment.save
  redirect_to article_path(@comment.article)
  end


end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
    
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    flash.notice = "Article '#{@article.title}' Deleted!"
    redirect_to tags_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<p>
Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> ago
<p>
Author: <%= comment.author_name %>
<p>
Says: "<%= comment.body %>"
<p>
------------------------------------

app/views/articles/edit.html.erb
<h1/>Edit Page</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<!-- BLOG HEADER -->
    <div class="inner-cover blog-header" style=
    "background-image:url('assets/images/preview/slider/vision.jpg')">
        <!--<span class="overlay"></span>-->

        <div class="text-center">
            <h1 class="big-title">FACTORY LABS BLOG</h1>

            <p>FIND OUT WHAT WE ARE UP TO</p>
        </div>
    </div><!-- /BLOG HEADER -->
    <!-- Main Nav -->
    <%= render 'front/nav' %><!-- /Main Nav -->
    <!-- BLOG -->

    <section id="blog">
        <article class="container">
            <div class="row">
                <div class="left col-md-9">
                    <!-- blog item -->

                    <div class="item">
                        <% @articles.each do |article| %><!-- article title -->
                        <br>
                        <br>

                        <div class="item-title">
                            <h2><a href=
                            "#"><%= article.title %></a></h2><a class=
                            "scrollTo label label-default light" href="#">
                            date:</a> <a class=
                            "scrollTo label label-default light" href="#">
                            <%=article.comments.size %> Comments</a> <a class=
                            "label label-default light" href="#">Tags:
                            <% article.tags.each do |tag| %>
                            <%= link_to tag.name, tag_path(tag) %>
                            <% end %></a>
                        </div><!-- image -->

                        <figure>
                            <% if article.image.exists? %><%= image_tag article.image.url, size: "820x500" %><% else %><%= image_tag '1.png' %><% end %>
                        </figure><!-- blog short preview -->

                        <p>
                        <%= truncate(article.body, length: 250, seperator: '') %></p><!-- read more button -->
                        <%= link_to "Read More", article_path(article) %><br>
                        <br>

                        <div class="divider">
                            <!-- lines divider -->
                        </div><% end %>
                    </div><!-- /blog item -->
                    <!-- PAGINATION -->

                    <div class="text-center">
                        <ul class="pagination">
                            <li><a href="#"></a></li>

                            <li class="active"><a href="#">1</a></li>

                            <li><a href="#">2</a></li>

                            <li><a href="#">3</a></li>

                            <li><a href="#">4</a></li>

                            <li><a href="#">5</a></li>

                            <li><a href="#"></a></li>
                        </ul>
                    </div><!-- /PAGINATION -->
                </div><!-- SIDEBAR -->

                <div class="right col-md-3">
                    <!-- blog search -->

                    <div class="widget">
                        <h3>Blog Search</h3>

                        <form action="#" class=
                        "blog-search col-lg-12 nomargin nopadding" method=
                        "get">
                            <div class="input-group input-group-lg">
                                <input class="form-control" id="s" name="s"
                                placeholder="..." type="text">
                            </div>
                        </form>
                    </div><!-- categories -->

                    <div class="widget">
                        <h3>Categories</h3>

                        <ul>
                            <li>
                            <a><%= link_to "All Tags", tags_path %></a></li>

                            <li><a href=
                            "blog.html"><%= link_to "Create a New Article", new_article_path, class: "new_article" %></a></li>
                        </ul>
                    </div><!-- recent posts -->

                    <div class="widget">
                        <h3>Recent Posts</h3>

                        <ul>
                            <li><a href="blog-post.html">This is a Gallery
                            Post</a> <small>23 June 2013 / 12:43</small></li>

                            <li><a href="blog-post.html">Blog Post With Text
                            Only</a> <small>23 June 2013 / 12:43</small></li>

                            <li><a href="blog-post.html">This is an Audio
                            Post</a> <small>23 June 2013 / 12:43</small></li>

                            <li><a href="blog-post.html">This is a Video
                            Post</a> <small>23 June 2013 / 12:43</small></li>

                            <li><a href="blog-post.html">An awsome post</a>
                            <small>23 June 2013 / 12:43</small></li>
                        </ul>
                    </div>
                </div><!-- /SIDEBAR -->
            </div>
        </article>
    </section><!-- /BLOG -->

app/views/articles/new.html.erb
<h1/>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<% if @article.image.exists? %>
  <%= image_tag @article.image.url %>
<% else %>
  <%= image_tag '1.png' %>
<% end %>

<p>
<h1/>
  <%= @article.title %>
</h1>
<p/>
<%= @article.body %>
</p> 
Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
<%= render partial: 'comments/form' %>
<p>
<br/>
<h2/>Comment Section (<%= @article.comments.size %>)</h2>
<%= render partial: 'articles/comment', collection: @article.comments %>
<br/>
<br/>
<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
<%= link_to "edit", edit_article_path(@article) %>

app/views/author_sessions/new.html.erb
Login



<%= form_tag author_sessions_path, method: :post do %>
  

    <%= label_tag :email %>
    <%= text_field_tag :email %>
    

  

  

    <%= label_tag :password %>
    <%= password_field_tag :password %>
    

  

  

    <%= submit_tag "Login" %>
  

<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'authors/form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.email %></td>
        <td><%= author.password %></td>
        <td><%= author.password_confirmation %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'authorsform' %>

<%= link_to 'Back', authors_path %>




<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>IsisOne - Personal or Agency Portfolio</title>
    <meta name="description" content="" />
    <meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />

    <!--[if lt IE 9]>
      <script type="text/javascript" src="assets/plugins/lt-ie9/html5.js"></script>
      <script type="text/javascript" src="assets/plugins/lt-ie9/respond.min.js"></script>
      <script type="text/javascript" src="assets/plugins/lt-ie9/excanvas.compiled.js"></script>
    <![endif]--> 

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Dosis:300,400" rel="stylesheet" type="text/css" />


    <!-- CORE CSS FRAMEWORK -->
    <link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="assets/plugins/font-linecons/linecons.css" rel="stylesheet" type="text/css" />

    <!-- PLUGINS -->
    <link href="assets/css/superslides.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="assets/plugins/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css" />

    <!-- CSS TEMPLATE -->
    <link href="assets/css/reset.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/framework.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/typography.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/layout.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/blog.css" rel="stylesheet" type="text/css" />

    <!-- colors : demo only -->
    <link href="assets/css/color/blue.css" rel="alternate stylesheet" type="text/css" title="blue" />
    <link href="assets/css/color/orange.css" rel="alternate stylesheet" type="text/css" title="orange" />
    <link href="assets/css/color/green.css" rel="alternate stylesheet" type="text/css" title="green" />
    <link href="assets/css/color/red.css" rel="alternate stylesheet" type="text/css" title="red" />
    <link href="assets/css/color/yellow.css" rel="alternate stylesheet" type="text/css" title="yellow" />
    <link href="assets/css/color/gray.css" rel="alternate stylesheet" type="text/css" title="gray" />
    <link href="assets/css/color/pink.css" rel="alternate stylesheet" type="text/css" title="pink" />
    <link href="assets/css/color/mauve.css" rel="alternate stylesheet" type="text/css" title="mauve" />
    <link href="assets/css/color/green.css" rel="stylesheet" type="text/css" /><!-- default style : green-->

    <!-- ICONS -->
    <link rel="shortcut icon" href="assets/images/favicon.png" type="image/x-icon" />
    <link rel="icon" href="assets/images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="assets/images/favicon.ico" type="image/x-icon" />

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

    <!-- STYLESWITCHER -->
    <link href="assets/plugins/styleswitcher/styleswitcher.css" rel="stylesheet" type="text/css"/>

    <!-- Morenizr -->
    <script type="text/javascript" src="assets/plugins/modernizr.min.js"></script>
  </head>
  <body>


    <!-- STYLESWITCHER -->
    <div id="switcher">
      <div class="content-switcher" >        
        <h4>STYLE OPTIONS</h4>

        <p>Color Skin:</p>
        <ul style="width:150px;">            
          <li><a href="#" onclick="setActiveStyleSheet('blue'); return false;" class="color" style="background-color:#50657B"></a></li><!-- default -->
          <li><a href="#" onclick="setActiveStyleSheet('orange'); return false;" class="color" style="background-color:#F07057"></a></li>
          <li><a href="#" onclick="setActiveStyleSheet('green'); return false;" class="color" style="background-color:#7E8344"></a></li>
          <li><a href="#" onclick="setActiveStyleSheet('red'); return false;" class="color" style="background-color:#e93735"></a></li>
          <li><a href="#" onclick="setActiveStyleSheet('pink'); return false;" class="color" style="background-color:#f73f69"></a></li>
          <li><a href="#" onclick="setActiveStyleSheet('mauve'); return false;" class="color" style="background-color:#c91ac9"></a></li>
          <li><a href="#" onclick="setActiveStyleSheet('yellow'); return false;" class="color" style="background-color:#f1c40f"></a></li>
          <li><a href="#" onclick="setActiveStyleSheet('gray'); return false;" class="color" style="background-color:#333333"></a></li>
        </ul>        

        <p>Home Page Template:</p>
        <div class="styled-select">
          <select onchange="window.document.location.href=this.options[this.selectedIndex].value;">  
            
            <optgroup label="+ Personal">
              <option value="index-personal-full.html">01. Fullscreen Slider</option>
              <option value="index-personal-half.html">02. Halfscreen Slider</option>
              <option value="index-personal-half.html">03. Full Video</option>
            </optgroup>

            <optgroup label="+ Agency">
              <option value="index-agency-full.html">01. Fullscreen Slider</option>
              <option value="index-agency-half.html">02. Halfscreen Slider</option>
              <option value="index-agency-video.html">03. Full Video</option>
            </optgroup>

            <optgroup label="+ Application">
              <option value="index-application-full.html">01. Fullscreen Slider</option>
              <option value="index-application-half.html">02. Halfscreen Slider</option>
              <option value="index-application-video.html">03. Full Video</option>
            </optgroup>

            <optgroup label="Misc">
              <option value="countdown-image.html">Count Down - Image</option>
              <option value="countdown-video.html">Count Down - Video</option>
              <option value="index-video-full.html">404 Not Found</option>
              <option value="faq.html">Faq Page</option>
              <option value="text-page.html">Default Text Page</option>
            </optgroup>

          </select>
        </div>

        <div class="switcher-links">
          <a href="elements.html">elements.html</a>
          <a href="typography.html">typography.html</a>
          <a href="icons-fontawsome.html">icons-fontawsome.html</a>
          <a href="icons-linecons.html">icons-linecons.html</a>
        </div>

        <div id="hideSwitcher">&times;</div>
      </div>
    </div>
    <div id="showSwitcher"><i class="fa fa-tint"></i></div>
    <!-- /STYLESWITCHER -->


    <!-- BLOG HEADER -->
    <div class="inner-cover blog-header" style="background-image:url('assets/images/preview/slider/vision.jpg')">
      <!--<span class="overlay"></span>-->

      <div class="text-center">
        <h1 class="big-title">ISIS ONE . BLOG</h1>
        <p>THE TEMPLATE IS EASY TO SET UP</p>
      </div>
    </div>
    <!-- /BLOG HEADER -->



    <!-- Main Nav -->
    <header id="header">

      <nav class="navbar navbar-inverse" role="navigation"><!-- add "wihite" class for white nav bar -->
        <div class="container">

          <!-- Mobile Menu Button -->
          <button id="mobileMenu" class="fa fa-bars" type="button" data-toggle="collapse" data-target=".navbar-collapse"></button>

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <a class="navbar-brand" href="index-personal-full.html">
              <%= image_tag "l2.png",  %> 
              <!--
                Span class:
                  - dark
                  - white
                  - styleColor (if you select "green" style color, the color will be green).

                  You can combine them 
                  Example:
                    <span class="white">ISIS</span><span class="styleColor">ONE</span>
              -->
              <span class="">FACTORY LAB BLOG</span>
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <!-- Fullscreen Button - Unavailable for IE -->
            <a href="#" class="btn-fullscreen"><i class="fa fa-external-link"></i></a>

            <ul class="nav navbar-nav navbar-right">
              <li><a href="index-personal-full.html#home">Home</a></li>
              <li><a href="index-personal-full.html#about">About</a></li>
              <li><a href="index-personal-full.html#work">Work</a></li>
              <li><a href="index-personal-full.html#services">Services</a></li>
              <li class="active"><a href="blog.html">Blog</a></li>
              <li><a href="index-personal-full.html#contact">Contact</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->

        </div>
      </nav>

    </header>
    <!-- /Main Nav -->





            <!-- PAGINATION -->
            <div class="text-center">
              <ul class="pagination">
                <li><a href="#"><i class="fa fa-chevron-left"></i></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#"><i class="fa fa-chevron-right"></i></a></li>
              </ul>
            </div>
            <!-- /PAGINATION -->


          </div>


          <!-- SIDEBAR -->
          <div class="right col-md-3">

            <!-- blog search -->
            <div class="widget">

              <h3>Blog Search</h3>

              <form action="#" method="get" class="blog-search col-lg-12 nomargin nopadding">
                <div class="input-group input-group-lg">
                  <input type="text" class="form-control" name="s" id="s" placeholder="..." />
                  <span class="input-group-btn">
                    <button class="btn btn-primary"><i class="fa fa-search"></i></button>
                  </span>
                </div>
              </form>
            </div>

            <!-- recent work -->
            <div class="widget">

              <h3>Recent Work </h3>

              <a class="popup-image thumb" href="assets/images/preview/slider/1.jpg">
                <img src="assets/images/1x1.png" class="img-responsive" data-src="holder.js/85x85/#888:#555555/auto/" alt="img" />
              </a>
              <a class="popup-video thumb" href="http://www.youtube.com/watch?v=kh29_SERH0Y?rel=0">
                <img src="assets/images/1x1.png" class="ajax-project img-responsive" data-src="holder.js/85x85/#676767:#555555/auto/" alt="img" />
              </a>
              <a class="popup-video thumb" href="http://vimeo.com/23630702">
                <img src="assets/images/1x1.png" class="ajax-project img-responsive" data-src="holder.js/85x85/#888:#555555/auto/" alt="img" />
              </a>

              <a class="external ajax-project thumb" href="project-external-1.html">
                <img src="assets/images/1x1.png" class="ajax-project img-responsive" data-src="holder.js/85x85/#676767:#555555/auto/" alt="img" />
              </a>
              <a class="external ajax-project thumb" href="project-external-2.html">
                <img src="assets/images/1x1.png" class="ajax-project img-responsive" data-src="holder.js/85x85/#888:#555555/auto/" alt="img" />
              </a>
              <a class="external ajax-project thumb" href="project-external-3.html">
                <img src="assets/images/1x1.png" class="ajax-project img-responsive" data-src="holder.js/85x85/#676767:#555555/auto/" alt="img" />
              </a>

              <div class="clearfix"></div>
            </div>

            <!-- categories -->
            <div class="widget">

              <h3>Categories</h3>

              <ul>
                <li><a href="blog.html"><i class="fa fa-dot-circle-o"></i> Business</a></li>
                <li><a href="blog.html"><i class="fa fa-dot-circle-o"></i> Audio</a></li>
                <li><a href="blog.html"><i class="fa fa-dot-circle-o"></i> Creative</a></li>
                <li><a href="blog.html"><i class="fa fa-dot-circle-o"></i> Funny</a></li>
              </ul>

            </div>

            <!-- recent posts -->
            <div class="widget">

              <h3>Recent Posts</h3>

              <ul>
                <li><a href="blog-post.html"><i class="fa fa-sign-out"></i> This is a Gallery Post</a> <small>23 June 2013 / 12:43</small></li>
                <li><a href="blog-post.html"><i class="fa fa-sign-out"></i> Blog Post With Text Only</a> <small>23 June 2013 / 12:43</small></li>
                <li><a href="blog-post.html"><i class="fa fa-sign-out"></i> This is an Audio Post</a> <small>23 June 2013 / 12:43</small></li>
                <li><a href="blog-post.html"><i class="fa fa-sign-out"></i> This is a Video Post</a> <small>23 June 2013 / 12:43</small></li>
                <li><a href="blog-post.html"><i class="fa fa-sign-out"></i> An awsome post</a> <small>23 June 2013 / 12:43</small></li>
              </ul>

            </div>

          </div>
          <!-- /SIDEBAR -->

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @author.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @author.password_confirmation %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h2/>Post a Comment</h2>
<p>

<%= form_for [ @article, @comment ] do |f| %>
  
    <p>
    <%= f.label :author_name, "Your Name" %>
    <p>
    <%= f.text_field :author_name %>
  
    <p>
    <%= f.label :body, "Your Comment" %>
    <p>
    <%= f.text_area :body %>
  
    <p>
    <%= f.submit 'Submit' %>
  


<% end %>

app/views/front/_nav.html.erb
    <header id="header">
        <nav class="navbar navbar-inverse">
            <!-- add "wihite" class for white nav bar -->

            <div class="container">
                <!-- Mobile Menu Button -->
                <button class="fa fa-bars" data-target=".navbar-collapse"
                data-toggle="collapse" id="mobileMenu" type="button"></button> 
                <!-- Brand and toggle get grouped for better mobile display -->

                <div class="navbar-header">
                    <%= image_tag "l2a.png" %>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->

                <div class="collapse navbar-collapse" id=
                "bs-example-navbar-collapse-1">
                    <!-- Fullscreen Button - Unavailable for IE -->
                    <a class="btn-fullscreen" href="#"></a>

                    <ul class="nav navbar-nav navbar-right">
                        <li><% if logged_in? %></li>

                        <li><%= "Hey #{current_user.username}" %></li>

                        <li><%= link_to "(logout)", logout_path %></li>

                        <li>
                        <% else %><%= link_to "(login)", login_path %><% end %></li>

                        <li><%= link_to "Blog", articles_path %></li>

                        <li><a class="scrollTo" href="#contact">Contact</a>
                        </li>
                        <li><%= link_to "HOME", root_path %>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
    </header>

app/views/tags/index.html.erb
<h1/>All Tags</h1>


  <% @tags.each do |tag| %>
    
      <p/>
      <%= link_to tag.name, tag_path(tag) %>
      </p>
      
  <% end %>

<%= link_to "<< Back to Articles List", articles_path %>